### ISSUE TITLE
Missing offset(), count() and all()

### ISSUE THREAD

**Issue by MarcelHekkert** [mattbit/flat#1]
I am missing some functions like offset(), count(), all() Which will also make somepaging of the results more easily possible. I think it would be worth to has these.

I wrote some code that add count() and all(), but there might be a better implementation.

/src/Flat/Collection.php
 
    
    public function all()
    {
        return $this->store->scan();
    }

    public function count($criteria = NULL)
    {
        if($criteria) return count($this->onMatch($criteria));
        return $this->store->count();
    }

/src/Flat/Storage/DocumentStore.php

    public function count()
    {
        return count(glob($this->engine->getpath('*', $this->namespace)));
    }

/src/Flat/Storage/FilesystemEngine.php  (since path() is protected)

    public function getpath($id, $collection, $ext = NULL)
    {
        return $this->path($id, $collection, $ext);
    } 

This now enables 2 new functions, where 'postid' in comment is a reference:

    $db->collection('posts')->find(['_id' => $id]);  // Get Post
    $db->collection('comment')->count(['postid' => $id]);  // Count Comments for post
    $db->collection('posts')->all();  // Get All Posts

**Comment by mattbit** [comment]
Hi @MarcelHekkert, thanks for your suggestions.

The `all` function you are describing is equivalent to use an empty criteria with `find` (by the way, this is consistent with the mongodb API from which I steal ideas). For example:

```php
$db->collection('posts')->find([]);  // returns all the posts
```
I’ve just made the criteria optional, so you can use simply:

```php
$db->collection('posts')->find();
```

I implemented the `count` using the iterator already present in the `FilesystemEngine`:

```php
$db->collection('posts')->count();  // counts all the posts
```

I will add the possibility to specify a criteria for `count` later.

Tell me if I’ve missed something ;)

**Comment by MarcelHekkert** [comment]
Hey there @mattbit Thanks for acting so quickly. I am not (that) familiar yet with NoSql and Mongo. It's great though you keep your library in line with Mongo, should a site become bigger.

The count() on a collection like comments would be great, if inline with Mongo, it would allow to count files without having them go through a foreach.

The library is great for portabillity, which I'd like for a CMS project, so it might turn out to be a good match, so thanks for updating it!

ps: Not sure if this space is meant to chat, so it's ok to delete this after reading.

**Comment by mattbit** [comment]
> It's great though you keep your library in line with Mongo, should a site become bigger.

Yeah, that’s exactly the point! I see Flat as an easy way to set up quickly a minimal database for small projects, while also leaving open the possibility of replacing it with a real mongo database later.

**Comment by mattbit** [comment]
Now it is possible to specify criteria for the `count` function.

```php
$db->collection('posts')->count(["author" => "joe"]);
```
